#!/usr/bin/env python3
"""
Auto-discover vibe-coded repos using GitHub Search API.

Signals (ranked by strength):
  1. Co-Authored-By patterns in commits (Claude, Cursor, Copilot, Codeium, etc.)
  2. .cursorrules / .cursor/ config files
  3. AI-related topics/tags on repo
  4. Commit message patterns ("generated by", "vibe coded", etc.)

Outputs candidates.json with scored repos ready for PR creation.

Usage:
  python scripts/discover_repos.py                          # discover new repos
  python scripts/discover_repos.py --min-score 30           # custom threshold
  python scripts/discover_repos.py --max-candidates 15      # more candidates
  python scripts/discover_repos.py --dry-run                # preview without writing

Requires: GITHUB_TOKEN env var (for higher rate limits).
"""

import argparse
import json
import logging
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────

AI_COAUTHOR_PATTERNS = [
    "Co-authored-by: Claude",
    "Co-authored-by: Cursor",
    "Co-authored-by: GitHub Copilot",
    "Co-authored-by: Copilot",
    "Co-authored-by: Codeium",
    "Co-authored-by: Windsurf",
    "Co-authored-by: Devin",
    "Co-authored-by: Amazon Q",
    "Co-authored-by: Tabnine",
    "Co-authored-by: Cody",
]

AI_COMMIT_MESSAGE_PATTERNS = [
    "generated by",
    "built with cursor",
    "vibe coded",
    "ai-assisted",
    "ai generated",
    "created with v0",
    "built with bolt",
    "generated with claude",
]

AI_TOPIC_TAGS = [
    "vibe-coding",
    "ai-generated",
    "ai-assisted",
    "cursor",
    "copilot",
    "claude",
    "ai-coding",
]

ALLOWED_LICENSES = {
    "mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause",
    "isc", "mpl-2.0", "unlicense", "0bsd",
}

# Files that indicate it's a real project
PROJECT_INDICATORS = [
    "package.json", "pyproject.toml", "Cargo.toml", "go.mod",
    "pom.xml", "build.gradle", "requirements.txt", "setup.py",
]

GITHUB_API = "https://api.github.com"
SEARCH_API = f"{GITHUB_API}/search"

# Rate limit: 30 search requests/min with token
SEARCH_DELAY = 2.5  # seconds between search requests


# ──────────────────────────────────────────────────────────────
# GitHub API helpers
# ──────────────────────────────────────────────────────────────

def get_headers(token: str | None) -> dict:
    headers = {"Accept": "application/vnd.github.v3+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def github_search(endpoint: str, query: str, token: str | None, per_page: int = 30) -> dict:
    """Execute a GitHub search with rate limit handling."""
    url = f"{SEARCH_API}/{endpoint}"
    params = {"q": query, "per_page": per_page, "sort": "updated", "order": "desc"}
    headers = get_headers(token)

    # GitHub commit search requires a special accept header
    if endpoint == "commits":
        headers["Accept"] = "application/vnd.github.cloak-preview+json"

    for attempt in range(3):
        resp = requests.get(url, headers=headers, params=params, timeout=30)

        if resp.status_code == 200:
            return resp.json()
        elif resp.status_code == 403:
            # Rate limited — wait and retry
            reset_time = int(resp.headers.get("X-RateLimit-Reset", 0))
            wait = max(reset_time - int(time.time()), 10)
            logger.warning(f"Rate limited. Waiting {wait}s (attempt {attempt + 1}/3)")
            time.sleep(min(wait, 60))
        elif resp.status_code == 422:
            logger.warning(f"Validation error for query: {query[:80]}... — {resp.text[:200]}")
            return {"items": [], "total_count": 0}
        else:
            logger.error(f"GitHub API error {resp.status_code}: {resp.text[:200]}")
            return {"items": [], "total_count": 0}

    return {"items": [], "total_count": 0}


def get_repo_info(owner_repo: str, token: str | None) -> dict | None:
    """Fetch full repo metadata."""
    url = f"{GITHUB_API}/repos/{owner_repo}"
    resp = requests.get(url, headers=get_headers(token), timeout=15)
    if resp.status_code == 200:
        return resp.json()
    return None


def get_repo_commits(owner_repo: str, token: str | None, since_days: int = 90, per_page: int = 100) -> list:
    """Fetch recent commits for a repo."""
    since = (datetime.now(timezone.utc) - timedelta(days=since_days)).isoformat()
    url = f"{GITHUB_API}/repos/{owner_repo}/commits"
    params = {"since": since, "per_page": per_page}
    resp = requests.get(url, headers=get_headers(token), params=params, timeout=15)
    if resp.status_code == 200:
        return resp.json()
    return []


def check_file_exists(owner_repo: str, filepath: str, token: str | None) -> bool:
    """Check if a file exists in the repo's default branch."""
    url = f"{GITHUB_API}/repos/{owner_repo}/contents/{filepath}"
    resp = requests.get(url, headers=get_headers(token), timeout=10)
    return resp.status_code == 200


# ──────────────────────────────────────────────────────────────
# Discovery: find candidate repos
# ──────────────────────────────────────────────────────────────

def discover_from_coauthor_commits(token: str | None, since_days: int = 90) -> dict[str, list[str]]:
    """
    Search GitHub commits for AI co-author patterns.
    Returns {repo_full_name: [list of matching co-author strings]}.
    """
    since_date = (datetime.now(timezone.utc) - timedelta(days=since_days)).strftime("%Y-%m-%d")
    repo_signals: dict[str, list[str]] = {}

    for pattern in AI_COAUTHOR_PATTERNS:
        query = f'"{pattern}" committer-date:>{since_date}'
        logger.info(f"Searching commits: {pattern}")
        result = github_search("commits", query, token, per_page=30)
        time.sleep(SEARCH_DELAY)

        for item in result.get("items", []):
            repo = item.get("repository", {}).get("full_name", "")
            if repo:
                if repo not in repo_signals:
                    repo_signals[repo] = []
                repo_signals[repo].append(pattern)

    return repo_signals


def discover_from_topics(token: str | None, min_stars: int = 50, since_days: int = 90) -> set[str]:
    """Search repos by AI-related topics."""
    since_date = (datetime.now(timezone.utc) - timedelta(days=since_days)).strftime("%Y-%m-%d")
    repos = set()

    for topic in AI_TOPIC_TAGS:
        query = f"topic:{topic} stars:>{min_stars} pushed:>{since_date}"
        logger.info(f"Searching repos by topic: {topic}")
        result = github_search("repositories", query, token, per_page=20)
        time.sleep(SEARCH_DELAY)

        for item in result.get("items", []):
            repos.add(item["full_name"])

    return repos


def discover_from_cursorrules(token: str | None) -> set[str]:
    """Find repos that have .cursorrules file (strong Cursor signal)."""
    logger.info("Searching for repos with .cursorrules")
    query = "filename:.cursorrules path:/"
    result = github_search("code", query, token, per_page=30)
    time.sleep(SEARCH_DELAY)

    repos = set()
    for item in result.get("items", []):
        repo = item.get("repository", {}).get("full_name", "")
        if repo:
            repos.add(repo)

    return repos


# ──────────────────────────────────────────────────────────────
# Scoring
# ──────────────────────────────────────────────────────────────

def score_repo(
    owner_repo: str,
    token: str | None,
    coauthor_signals: list[str] | None = None,
    has_cursorrules: bool = False,
    has_topic_match: bool = False,
) -> dict:
    """
    Score a repo on 0-100 scale based on AI-authorship signals.
    Returns full scoring breakdown.
    """
    score = 0
    evidence = []

    # 1. Co-Authored-By signals (strongest — up to 40 pts)
    if coauthor_signals:
        unique_patterns = len(set(coauthor_signals))
        total_signals = len(coauthor_signals)
        if total_signals >= 5:
            score += 40
            evidence.append(f"{total_signals} AI co-authored commits ({unique_patterns} distinct tools)")
        elif total_signals >= 1:
            score += 20
            evidence.append(f"{total_signals} AI co-authored commits")

    # 2. .cursorrules file (15 pts)
    if has_cursorrules:
        score += 15
        evidence.append("Has .cursorrules config")

    # 3. AI topic tags (10 pts)
    if has_topic_match:
        score += 10
        evidence.append("AI-related topic tags")

    # 4. Fetch repo metadata for remaining signals
    repo_info = get_repo_info(owner_repo, token)
    if not repo_info:
        return {"repo": owner_repo, "score": 0, "evidence": ["ERROR: Could not fetch repo info"], "skip_reason": "api_error"}

    stars = repo_info.get("stargazers_count", 0)
    license_info = repo_info.get("license") or {}
    license_key = (license_info.get("spdx_id") or "").lower()
    language = repo_info.get("language") or ""
    topics = repo_info.get("topics", [])
    description = (repo_info.get("description") or "").lower()
    pushed_at = repo_info.get("pushed_at", "")
    archived = repo_info.get("archived", False)
    fork = repo_info.get("fork", False)

    # Skip conditions
    if archived:
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": "archived"}
    if fork:
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": "fork"}
    if stars < 50:
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": f"too_few_stars ({stars})"}
    if license_key and license_key not in ALLOWED_LICENSES and license_key != "noassertion":
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": f"license ({license_key})"}

    # 5. Stars bonus (up to 10 pts)
    if stars >= 500:
        score += 10
        evidence.append(f"{stars:,} stars")
    elif stars >= 100:
        score += 5
        evidence.append(f"{stars:,} stars")

    # 6. Active in last 30 days (5 pts)
    if pushed_at:
        try:
            pushed = datetime.fromisoformat(pushed_at.replace("Z", "+00:00"))
            if (datetime.now(timezone.utc) - pushed).days <= 30:
                score += 5
                evidence.append("Active in last 30 days")
        except ValueError:
            pass

    # 7. TypeScript or Python (5 pts)
    if language.lower() in ("typescript", "python", "javascript"):
        score += 5
        evidence.append(f"Primary language: {language}")

    # 8. Check commit messages for AI patterns (10 pts)
    commits = get_repo_commits(owner_repo, token, since_days=90, per_page=50)
    ai_commit_count = 0
    for commit in commits:
        msg = (commit.get("commit", {}).get("message") or "").lower()
        if any(p in msg for p in AI_COMMIT_MESSAGE_PATTERNS):
            ai_commit_count += 1
    if ai_commit_count > 0:
        score += 10
        evidence.append(f"{ai_commit_count} commits with AI-related messages")

    # 9. Check for AI topic tags we didn't already count
    if not has_topic_match:
        matching_topics = [t for t in topics if t in AI_TOPIC_TAGS]
        if matching_topics:
            score += 10
            evidence.append(f"Topics: {', '.join(matching_topics)}")

    # 10. AI keywords in description (5 pts)
    ai_desc_keywords = ["ai-assisted", "vibe coded", "built with ai", "cursor", "copilot", "claude"]
    if any(kw in description for kw in ai_desc_keywords):
        score += 5
        evidence.append("AI keywords in description")

    return {
        "repo": owner_repo,
        "score": score,
        "stars": stars,
        "language": language,
        "license": license_key or "unknown",
        "evidence": evidence,
        "topics": topics[:10],
    }


# ──────────────────────────────────────────────────────────────
# Main pipeline
# ──────────────────────────────────────────────────────────────

def load_existing_repos(repo_root: str) -> tuple[set[str], set[str]]:
    """Load training + eval repo lists to avoid duplicates."""
    training_file = os.path.join(repo_root, "rlaif", "repos_training.json")
    training_repos = set()
    eval_repos = set()

    if os.path.exists(training_file):
        with open(training_file) as f:
            data = json.load(f)
        training_repos = set(data.get("repos", []))
        eval_repos = set(data.get("_eval_repos_DO_NOT_ADD", []))

    return training_repos, eval_repos


def run_discovery(
    repo_root: str,
    min_score: int = 30,
    max_candidates: int = 10,
    since_days: int = 90,
    dry_run: bool = False,
) -> list[dict]:
    """
    Full discovery pipeline:
    1. Search for repos with AI signals
    2. Score each candidate
    3. Filter and rank
    4. Output candidates.json
    """
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        logger.warning("No GITHUB_TOKEN set — API rate limits will be very low (10 searches/min)")

    # Load existing repos to skip
    training_repos, eval_repos = load_existing_repos(repo_root)
    blocklist = training_repos | eval_repos
    logger.info(f"Blocklist: {len(blocklist)} repos ({len(training_repos)} training, {len(eval_repos)} eval)")

    # Step 1: Discover candidates from multiple sources
    logger.info("=== Step 1: Discovering candidates ===")

    coauthor_repos = discover_from_coauthor_commits(token, since_days)
    topic_repos = discover_from_topics(token, min_stars=50, since_days=since_days)
    cursorrules_repos = discover_from_cursorrules(token)

    # Merge all candidate repos
    all_candidates = set(coauthor_repos.keys()) | topic_repos | cursorrules_repos
    all_candidates -= blocklist  # Remove already-known repos

    logger.info(f"Found {len(all_candidates)} unique candidates after dedup")
    logger.info(f"  - Co-author signal: {len(coauthor_repos)} repos")
    logger.info(f"  - Topic match: {len(topic_repos)} repos")
    logger.info(f"  - .cursorrules: {len(cursorrules_repos)} repos")

    # Step 2: Score each candidate
    logger.info("=== Step 2: Scoring candidates ===")
    scored = []
    for i, repo in enumerate(sorted(all_candidates)):
        logger.info(f"  Scoring [{i+1}/{len(all_candidates)}]: {repo}")
        result = score_repo(
            repo,
            token,
            coauthor_signals=coauthor_repos.get(repo),
            has_cursorrules=(repo in cursorrules_repos),
            has_topic_match=(repo in topic_repos),
        )
        scored.append(result)
        time.sleep(0.5)  # Be kind to the API

    # Step 3: Filter and rank
    logger.info("=== Step 3: Filtering and ranking ===")
    qualified = [r for r in scored if r.get("score", 0) >= min_score and "skip_reason" not in r]
    qualified.sort(key=lambda x: x["score"], reverse=True)
    candidates = qualified[:max_candidates]

    skipped = [r for r in scored if "skip_reason" in r]
    below_threshold = [r for r in scored if r.get("score", 0) < min_score and "skip_reason" not in r]

    logger.info(f"Results: {len(candidates)} candidates (score >= {min_score})")
    logger.info(f"  Skipped: {len(skipped)} (archived/fork/license/stars)")
    logger.info(f"  Below threshold: {len(below_threshold)}")

    for c in candidates:
        logger.info(f"  ✓ {c['repo']} (score={c['score']}, stars={c.get('stars', '?')})")

    # Step 4: Output
    if not dry_run:
        output_dir = os.path.join(repo_root, "results")
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, "candidates.json")
        output = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "discovery_params": {
                "min_score": min_score,
                "max_candidates": max_candidates,
                "since_days": since_days,
            },
            "summary": {
                "total_searched": len(all_candidates),
                "qualified": len(qualified),
                "returned": len(candidates),
                "skipped": len(skipped),
                "below_threshold": len(below_threshold),
            },
            "candidates": candidates,
            "skipped": skipped[:20],  # Keep top 20 skipped for transparency
        }
        with open(output_path, "w") as f:
            json.dump(output, f, indent=2)
        logger.info(f"Wrote {output_path}")

    return candidates


def update_training_repos(repo_root: str, new_repos: list[str]) -> bool:
    """Add new repos to repos_training.json. Returns True if modified."""
    training_file = os.path.join(repo_root, "rlaif", "repos_training.json")
    with open(training_file) as f:
        data = json.load(f)

    existing = set(data.get("repos", []))
    to_add = [r for r in new_repos if r not in existing]

    if not to_add:
        logger.info("No new repos to add")
        return False

    data["repos"].extend(to_add)

    # Update categories comment
    categories = data.get("_categories", {})
    discovered_list = ", ".join(to_add)
    categories["auto_discovered"] = f"{discovered_list} ({len(to_add)})"
    data["_categories"] = categories

    with open(training_file, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    logger.info(f"Added {len(to_add)} repos to {training_file}")
    return True


# ──────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Discover vibe-coded repos via GitHub API")
    parser.add_argument("--min-score", type=int, default=30, help="Minimum score threshold (default: 30)")
    parser.add_argument("--max-candidates", type=int, default=10, help="Max repos to return (default: 10)")
    parser.add_argument("--since-days", type=int, default=90, help="Look back period in days (default: 90)")
    parser.add_argument("--dry-run", action="store_true", help="Preview only, don't write files")
    parser.add_argument("--update-training", action="store_true", help="Also update repos_training.json")
    parser.add_argument("--repo-root", default=".", help="Path to driftbench repo root")
    args = parser.parse_args()

    candidates = run_discovery(
        repo_root=args.repo_root,
        min_score=args.min_score,
        max_candidates=args.max_candidates,
        since_days=args.since_days,
        dry_run=args.dry_run,
    )

    if not candidates:
        logger.info("No candidates found")
        return

    # Print summary table
    print("\n" + "=" * 70)
    print(f"{'Repo':<40} {'Score':>5} {'Stars':>7} {'Evidence'}")
    print("-" * 70)
    for c in candidates:
        evidence_short = "; ".join(c.get("evidence", [])[:2])
        print(f"{c['repo']:<40} {c['score']:>5} {c.get('stars', '?'):>7} {evidence_short[:40]}")
    print("=" * 70)

    if args.update_training and not args.dry_run:
        new_repos = [c["repo"] for c in candidates]
        update_training_repos(args.repo_root, new_repos)


if __name__ == "__main__":
    main()
