#!/usr/bin/env python3
"""
Auto-discover high-quality training repos using GitHub Search API.

Two discovery tracks:
  A. AI-signal track: repos with AI co-authorship patterns (vibe-coded)
  B. Enterprise track: mature production repos across diverse domains

Quality signals (all repos scored on):
  - AI co-authorship (commit patterns, .cursorrules, topics)
  - Code maturity: CI/CD, tests, contributor count, codebase age
  - Production indicators: stars, activity, license, language
  - Domain diversity: auth, payments, APIs, infra, not just AI tools

Outputs candidates.json with scored repos ready for PR creation.

Usage:
  python scripts/discover_repos.py                          # both tracks
  python scripts/discover_repos.py --track ai               # AI-signal only
  python scripts/discover_repos.py --track enterprise        # enterprise only
  python scripts/discover_repos.py --min-score 40           # higher threshold
  python scripts/discover_repos.py --max-candidates 15      # more candidates
  python scripts/discover_repos.py --dry-run                # preview without writing

Requires: GITHUB_TOKEN env var (for higher rate limits).
"""

import argparse
import json
import logging
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────

AI_COAUTHOR_PATTERNS = [
    "Co-authored-by: Claude",
    "Co-authored-by: Cursor",
    "Co-authored-by: GitHub Copilot",
    "Co-authored-by: Copilot",
    "Co-authored-by: Codeium",
    "Co-authored-by: Windsurf",
    "Co-authored-by: Devin",
    "Co-authored-by: Amazon Q",
    "Co-authored-by: Tabnine",
    "Co-authored-by: Cody",
]

AI_COMMIT_MESSAGE_PATTERNS = [
    "generated by",
    "built with cursor",
    "vibe coded",
    "ai-assisted",
    "ai generated",
    "created with v0",
    "built with bolt",
    "generated with claude",
]

AI_TOPIC_TAGS = [
    "vibe-coding",
    "ai-generated",
    "ai-assisted",
    "cursor",
    "copilot",
    "claude",
    "ai-coding",
]

ALLOWED_LICENSES = {
    "mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause",
    "isc", "mpl-2.0", "unlicense", "0bsd",
}

# Files that indicate it's a real project
PROJECT_INDICATORS = [
    "package.json", "pyproject.toml", "Cargo.toml", "go.mod",
    "pom.xml", "build.gradle", "requirements.txt", "setup.py",
]

# Enterprise domain search queries — find production repos across diverse verticals
# These are the domains where Rigour's customers actually work, not just AI tools
ENTERPRISE_SEARCH_QUERIES = [
    # Auth & Identity
    'topic:authentication stars:>500 pushed:>{since_date} language:TypeScript',
    'topic:oauth stars:>300 pushed:>{since_date}',
    'topic:authorization stars:>300 pushed:>{since_date}',
    # Payments & Fintech
    'topic:payments stars:>300 pushed:>{since_date}',
    'topic:fintech stars:>300 pushed:>{since_date}',
    'topic:stripe stars:>200 pushed:>{since_date} language:TypeScript',
    # API & Backend
    'topic:rest-api stars:>500 pushed:>{since_date} language:TypeScript',
    'topic:graphql stars:>500 pushed:>{since_date}',
    'topic:microservices stars:>300 pushed:>{since_date}',
    # Infrastructure & DevOps
    'topic:kubernetes stars:>500 pushed:>{since_date} language:Go',
    'topic:monitoring stars:>300 pushed:>{since_date}',
    'topic:ci-cd stars:>300 pushed:>{since_date}',
    # Data & Database
    'topic:orm stars:>300 pushed:>{since_date}',
    'topic:database stars:>500 pushed:>{since_date} language:TypeScript',
    # Security
    'topic:security stars:>300 pushed:>{since_date}',
    'topic:vulnerability-detection stars:>200 pushed:>{since_date}',
    # Frontend at scale
    'topic:design-system stars:>500 pushed:>{since_date}',
    'topic:component-library stars:>500 pushed:>{since_date}',
    # SaaS / Full-stack
    'topic:saas stars:>300 pushed:>{since_date}',
    'topic:cms stars:>500 pushed:>{since_date}',
    'topic:e-commerce stars:>300 pushed:>{since_date}',
]

GITHUB_API = "https://api.github.com"
SEARCH_API = f"{GITHUB_API}/search"

# Rate limit: 30 search requests/min with token
SEARCH_DELAY = 2.5  # seconds between search requests


# ──────────────────────────────────────────────────────────────
# GitHub API helpers
# ──────────────────────────────────────────────────────────────

def get_headers(token: str | None) -> dict:
    headers = {"Accept": "application/vnd.github.v3+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def github_search(endpoint: str, query: str, token: str | None, per_page: int = 30) -> dict:
    """Execute a GitHub search with rate limit handling."""
    url = f"{SEARCH_API}/{endpoint}"
    params = {"q": query, "per_page": per_page, "sort": "updated", "order": "desc"}
    headers = get_headers(token)

    # GitHub commit search requires a special accept header
    if endpoint == "commits":
        headers["Accept"] = "application/vnd.github.cloak-preview+json"

    for attempt in range(3):
        resp = requests.get(url, headers=headers, params=params, timeout=30)

        if resp.status_code == 200:
            return resp.json()
        elif resp.status_code == 403:
            # Rate limited — wait and retry
            reset_time = int(resp.headers.get("X-RateLimit-Reset", 0))
            wait = max(reset_time - int(time.time()), 10)
            logger.warning(f"Rate limited. Waiting {wait}s (attempt {attempt + 1}/3)")
            time.sleep(min(wait, 60))
        elif resp.status_code == 422:
            logger.warning(f"Validation error for query: {query[:80]}... — {resp.text[:200]}")
            return {"items": [], "total_count": 0}
        else:
            logger.error(f"GitHub API error {resp.status_code}: {resp.text[:200]}")
            return {"items": [], "total_count": 0}

    return {"items": [], "total_count": 0}


def get_repo_info(owner_repo: str, token: str | None) -> dict | None:
    """Fetch full repo metadata."""
    url = f"{GITHUB_API}/repos/{owner_repo}"
    resp = requests.get(url, headers=get_headers(token), timeout=15)
    if resp.status_code == 200:
        return resp.json()
    return None


def get_repo_commits(owner_repo: str, token: str | None, since_days: int = 90, per_page: int = 100) -> list:
    """Fetch recent commits for a repo."""
    since = (datetime.now(timezone.utc) - timedelta(days=since_days)).isoformat()
    url = f"{GITHUB_API}/repos/{owner_repo}/commits"
    params = {"since": since, "per_page": per_page}
    resp = requests.get(url, headers=get_headers(token), params=params, timeout=15)
    if resp.status_code == 200:
        return resp.json()
    return []


def check_file_exists(owner_repo: str, filepath: str, token: str | None) -> bool:
    """Check if a file exists in the repo's default branch."""
    url = f"{GITHUB_API}/repos/{owner_repo}/contents/{filepath}"
    resp = requests.get(url, headers=get_headers(token), timeout=10)
    return resp.status_code == 200


# ──────────────────────────────────────────────────────────────
# Discovery: find candidate repos
# ──────────────────────────────────────────────────────────────

def discover_from_coauthor_commits(token: str | None, since_days: int = 90) -> dict[str, list[str]]:
    """
    Search GitHub commits for AI co-author patterns.
    Returns {repo_full_name: [list of matching co-author strings]}.
    """
    since_date = (datetime.now(timezone.utc) - timedelta(days=since_days)).strftime("%Y-%m-%d")
    repo_signals: dict[str, list[str]] = {}

    for pattern in AI_COAUTHOR_PATTERNS:
        query = f'"{pattern}" committer-date:>{since_date}'
        logger.info(f"Searching commits: {pattern}")
        result = github_search("commits", query, token, per_page=30)
        time.sleep(SEARCH_DELAY)

        for item in result.get("items", []):
            repo = item.get("repository", {}).get("full_name", "")
            if repo:
                if repo not in repo_signals:
                    repo_signals[repo] = []
                repo_signals[repo].append(pattern)

    return repo_signals


def discover_from_topics(token: str | None, min_stars: int = 50, since_days: int = 90) -> set[str]:
    """Search repos by AI-related topics."""
    since_date = (datetime.now(timezone.utc) - timedelta(days=since_days)).strftime("%Y-%m-%d")
    repos = set()

    for topic in AI_TOPIC_TAGS:
        query = f"topic:{topic} stars:>{min_stars} pushed:>{since_date}"
        logger.info(f"Searching repos by topic: {topic}")
        result = github_search("repositories", query, token, per_page=20)
        time.sleep(SEARCH_DELAY)

        for item in result.get("items", []):
            repos.add(item["full_name"])

    return repos


def discover_from_cursorrules(token: str | None) -> set[str]:
    """Find repos that have .cursorrules file (strong Cursor signal)."""
    logger.info("Searching for repos with .cursorrules")
    query = "filename:.cursorrules path:/"
    result = github_search("code", query, token, per_page=30)
    time.sleep(SEARCH_DELAY)

    repos = set()
    for item in result.get("items", []):
        repo = item.get("repository", {}).get("full_name", "")
        if repo:
            repos.add(repo)

    return repos


def discover_enterprise_repos(token: str | None, since_days: int = 90) -> set[str]:
    """
    Discover production-grade repos across diverse enterprise domains.
    These repos have real drift patterns: staleness, security regressions,
    architecture violations — the patterns Rigour's customers actually face.
    """
    since_date = (datetime.now(timezone.utc) - timedelta(days=since_days)).strftime("%Y-%m-%d")
    repos = set()

    for query_template in ENTERPRISE_SEARCH_QUERIES:
        query = query_template.format(since_date=since_date)
        logger.info(f"Enterprise search: {query[:60]}...")
        result = github_search("repositories", query, token, per_page=10)
        time.sleep(SEARCH_DELAY)

        for item in result.get("items", []):
            repos.add(item["full_name"])

    logger.info(f"Enterprise track found {len(repos)} unique repos")
    return repos


def get_repo_quality_signals(owner_repo: str, token: str | None) -> dict:
    """
    Fetch code quality indicators that predict whether a repo produces
    good governance training data: CI/CD, tests, contributor count, size.
    """
    signals = {
        "has_ci": False,
        "has_tests": False,
        "contributor_count": 0,
        "age_days": 0,
    }

    # Check for CI/CD pipeline (GitHub Actions)
    url = f"{GITHUB_API}/repos/{owner_repo}/contents/.github/workflows"
    resp = requests.get(url, headers=get_headers(token), timeout=10)
    if resp.status_code == 200:
        workflows = resp.json()
        if isinstance(workflows, list) and len(workflows) > 0:
            signals["has_ci"] = True

    time.sleep(0.3)

    # Check for test directories
    for test_dir in ["tests", "test", "__tests__", "spec"]:
        url = f"{GITHUB_API}/repos/{owner_repo}/contents/{test_dir}"
        resp = requests.get(url, headers=get_headers(token), timeout=10)
        if resp.status_code == 200:
            signals["has_tests"] = True
            break
        time.sleep(0.2)

    # Get contributor count (first page — if 30+ contributors, that's a big team)
    url = f"{GITHUB_API}/repos/{owner_repo}/contributors"
    resp = requests.get(url, headers=get_headers(token), params={"per_page": 30}, timeout=10)
    if resp.status_code == 200:
        contributors = resp.json()
        if isinstance(contributors, list):
            signals["contributor_count"] = len(contributors)

    return signals


# ──────────────────────────────────────────────────────────────
# Scoring
# ──────────────────────────────────────────────────────────────

def score_repo(
    owner_repo: str,
    token: str | None,
    coauthor_signals: list[str] | None = None,
    has_cursorrules: bool = False,
    has_topic_match: bool = False,
    is_enterprise_track: bool = False,
) -> dict:
    """
    Score a repo on 0-100 scale based on training data quality potential.

    Scoring categories:
      A. AI-authorship signals (up to 40 pts) — vibe-coded repos
      B. Code maturity (up to 30 pts) — CI/CD, tests, contributors, age
      C. Production indicators (up to 30 pts) — stars, activity, language

    Both AI-signal and enterprise repos go through the same scorer.
    Enterprise repos score high on B+C even without A.
    """
    score = 0
    evidence = []

    # ── A. AI-Authorship Signals (up to 40 pts) ──────────────

    # 1. Co-Authored-By signals (strongest — up to 30 pts)
    if coauthor_signals:
        unique_patterns = len(set(coauthor_signals))
        total_signals = len(coauthor_signals)
        if total_signals >= 5:
            score += 30
            evidence.append(f"{total_signals} AI co-authored commits ({unique_patterns} distinct tools)")
        elif total_signals >= 1:
            score += 15
            evidence.append(f"{total_signals} AI co-authored commits")

    # 2. .cursorrules file (5 pts)
    if has_cursorrules:
        score += 5
        evidence.append("Has .cursorrules config")

    # 3. AI topic tags (5 pts)
    if has_topic_match:
        score += 5
        evidence.append("AI-related topic tags")

    # ── Fetch repo metadata ──────────────────────────────────

    repo_info = get_repo_info(owner_repo, token)
    if not repo_info:
        return {"repo": owner_repo, "score": 0, "evidence": ["ERROR: Could not fetch repo info"], "skip_reason": "api_error"}

    stars = repo_info.get("stargazers_count", 0)
    license_info = repo_info.get("license") or {}
    license_key = (license_info.get("spdx_id") or "").lower()
    language = repo_info.get("language") or ""
    topics = repo_info.get("topics", [])
    description = (repo_info.get("description") or "").lower()
    pushed_at = repo_info.get("pushed_at", "")
    created_at = repo_info.get("created_at", "")
    archived = repo_info.get("archived", False)
    fork = repo_info.get("fork", False)
    size_kb = repo_info.get("size", 0)  # repo size in KB

    # ── Skip conditions (harder filters) ─────────────────────

    if archived:
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": "archived"}
    if fork:
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": "fork"}
    # Raised from 50 → 200 stars. Weekend projects don't teach governance.
    if stars < 200:
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": f"too_few_stars ({stars})"}
    if license_key and license_key not in ALLOWED_LICENSES and license_key != "noassertion":
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": f"license ({license_key})"}
    # Skip tiny repos — not enough code to learn patterns from
    if size_kb < 500:  # less than 500KB total
        return {"repo": owner_repo, "score": 0, "evidence": evidence, "skip_reason": f"too_small ({size_kb}KB)"}

    # ── B. Code Maturity (up to 30 pts) ──────────────────────

    quality = get_repo_quality_signals(owner_repo, token)

    # 4. Has CI/CD pipeline (10 pts) — production-ready code
    if quality["has_ci"]:
        score += 10
        evidence.append("Has CI/CD pipeline")

    # 5. Has test suite (10 pts) — maintainable, testable code
    if quality["has_tests"]:
        score += 10
        evidence.append("Has test suite")

    # 6. Team-developed (up to 10 pts) — not a solo project
    contributors = quality["contributor_count"]
    if contributors >= 20:
        score += 10
        evidence.append(f"{contributors}+ contributors (large team)")
    elif contributors >= 10:
        score += 7
        evidence.append(f"{contributors} contributors")
    elif contributors >= 5:
        score += 4
        evidence.append(f"{contributors} contributors")

    # ── C. Production Indicators (up to 30 pts) ──────────────

    # 7. Stars (up to 10 pts)
    if stars >= 5000:
        score += 10
        evidence.append(f"{stars:,} stars (major project)")
    elif stars >= 1000:
        score += 7
        evidence.append(f"{stars:,} stars")
    elif stars >= 500:
        score += 5
        evidence.append(f"{stars:,} stars")
    else:
        score += 2
        evidence.append(f"{stars:,} stars")

    # 8. Active in last 30 days (5 pts)
    if pushed_at:
        try:
            pushed = datetime.fromisoformat(pushed_at.replace("Z", "+00:00"))
            if (datetime.now(timezone.utc) - pushed).days <= 30:
                score += 5
                evidence.append("Active in last 30 days")
        except ValueError:
            pass

    # 9. Mature project — created > 1 year ago (5 pts)
    if created_at:
        try:
            created = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            age_days = (datetime.now(timezone.utc) - created).days
            if age_days > 365:
                score += 5
                evidence.append(f"Mature ({age_days // 365}+ years old)")
        except ValueError:
            pass

    # 10. TypeScript, Python, Go, Rust (5 pts) — languages Rigour supports
    supported_languages = {"typescript", "python", "javascript", "go", "rust", "java"}
    if language.lower() in supported_languages:
        score += 5
        evidence.append(f"Primary language: {language}")

    # 11. Check commit messages for AI patterns (5 pts) — bonus for AI-signal track
    if not is_enterprise_track:
        commits = get_repo_commits(owner_repo, token, since_days=90, per_page=50)
        ai_commit_count = 0
        for commit in commits:
            msg = (commit.get("commit", {}).get("message") or "").lower()
            if any(p in msg for p in AI_COMMIT_MESSAGE_PATTERNS):
                ai_commit_count += 1
        if ai_commit_count > 0:
            score += 5
            evidence.append(f"{ai_commit_count} commits with AI-related messages")

    # Track which discovery track found this repo
    track = "enterprise" if is_enterprise_track else "ai-signal"

    return {
        "repo": owner_repo,
        "score": score,
        "stars": stars,
        "language": language,
        "license": license_key or "unknown",
        "evidence": evidence,
        "topics": topics[:10],
        "track": track,
        "quality": {
            "has_ci": quality["has_ci"],
            "has_tests": quality["has_tests"],
            "contributors": quality["contributor_count"],
        },
    }


# ──────────────────────────────────────────────────────────────
# Main pipeline
# ──────────────────────────────────────────────────────────────

def load_existing_repos(repo_root: str) -> tuple[set[str], set[str]]:
    """Load training + eval repo lists to avoid duplicates."""
    training_file = os.path.join(repo_root, "rlaif", "repos_training.json")
    training_repos = set()
    eval_repos = set()

    if os.path.exists(training_file):
        with open(training_file) as f:
            data = json.load(f)
        training_repos = set(data.get("repos", []))
        eval_repos = set(data.get("_eval_repos_DO_NOT_ADD", []))

    return training_repos, eval_repos


def run_discovery(
    repo_root: str,
    min_score: int = 40,
    max_candidates: int = 15,
    since_days: int = 90,
    dry_run: bool = False,
    track: str = "both",
) -> list[dict]:
    """
    Full discovery pipeline with two tracks:
      A. AI-signal: repos with AI co-authorship (vibe-coded)
      B. Enterprise: mature production repos across diverse domains

    Both tracks go through the same quality scorer.
    Final list balances AI-signal and enterprise repos.
    """
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        logger.warning("No GITHUB_TOKEN set — API rate limits will be very low (10 searches/min)")

    # Load existing repos to skip
    training_repos, eval_repos = load_existing_repos(repo_root)
    blocklist = training_repos | eval_repos
    logger.info(f"Blocklist: {len(blocklist)} repos ({len(training_repos)} training, {len(eval_repos)} eval)")

    # ── Track A: AI-signal discovery ─────────────────────────
    ai_candidates: set[str] = set()
    coauthor_repos: dict[str, list[str]] = {}
    topic_repos: set[str] = set()
    cursorrules_repos: set[str] = set()

    if track in ("both", "ai"):
        logger.info("=== Track A: AI-Signal Discovery ===")
        coauthor_repos = discover_from_coauthor_commits(token, since_days)
        topic_repos = discover_from_topics(token, min_stars=200, since_days=since_days)
        cursorrules_repos = discover_from_cursorrules(token)
        ai_candidates = set(coauthor_repos.keys()) | topic_repos | cursorrules_repos
        ai_candidates -= blocklist
        logger.info(f"AI track: {len(ai_candidates)} candidates")
        logger.info(f"  - Co-author signal: {len(coauthor_repos)} repos")
        logger.info(f"  - Topic match: {len(topic_repos)} repos")
        logger.info(f"  - .cursorrules: {len(cursorrules_repos)} repos")

    # ── Track B: Enterprise discovery ────────────────────────
    enterprise_candidates: set[str] = set()

    if track in ("both", "enterprise"):
        logger.info("=== Track B: Enterprise Discovery ===")
        enterprise_candidates = discover_enterprise_repos(token, since_days)
        enterprise_candidates -= blocklist
        enterprise_candidates -= ai_candidates  # No overlap
        logger.info(f"Enterprise track: {len(enterprise_candidates)} candidates")

    all_candidates = ai_candidates | enterprise_candidates
    logger.info(f"Total unique candidates: {len(all_candidates)}")

    # ── Score all candidates ─────────────────────────────────
    logger.info("=== Scoring candidates ===")
    scored = []
    for i, repo in enumerate(sorted(all_candidates)):
        is_enterprise = repo in enterprise_candidates
        logger.info(f"  Scoring [{i+1}/{len(all_candidates)}] ({'enterprise' if is_enterprise else 'ai-signal'}): {repo}")
        result = score_repo(
            repo,
            token,
            coauthor_signals=coauthor_repos.get(repo),
            has_cursorrules=(repo in cursorrules_repos),
            has_topic_match=(repo in topic_repos),
            is_enterprise_track=is_enterprise,
        )
        scored.append(result)
        time.sleep(0.5)  # Be kind to the API

    # ── Filter and rank with diversity ───────────────────────
    logger.info("=== Filtering and ranking ===")
    qualified = [r for r in scored if r.get("score", 0) >= min_score and "skip_reason" not in r]
    qualified.sort(key=lambda x: x["score"], reverse=True)

    # Ensure diversity: at least 40% from each active track
    if track == "both" and len(qualified) > 4:
        ai_qualified = [r for r in qualified if r.get("track") == "ai-signal"]
        ent_qualified = [r for r in qualified if r.get("track") == "enterprise"]
        min_per_track = max(2, max_candidates * 2 // 5)  # 40% floor

        candidates = []
        # Take top from each track first
        candidates.extend(ai_qualified[:min_per_track])
        candidates.extend(ent_qualified[:min_per_track])
        # Fill remaining with highest-scored from either track
        remaining_pool = [r for r in qualified if r not in candidates]
        remaining_pool.sort(key=lambda x: x["score"], reverse=True)
        candidates.extend(remaining_pool[:max(0, max_candidates - len(candidates))])
        # Re-sort final list by score
        candidates.sort(key=lambda x: x["score"], reverse=True)
        candidates = candidates[:max_candidates]
    else:
        candidates = qualified[:max_candidates]

    skipped = [r for r in scored if "skip_reason" in r]
    below_threshold = [r for r in scored if r.get("score", 0) < min_score and "skip_reason" not in r]

    logger.info(f"Results: {len(candidates)} candidates (score >= {min_score})")
    ai_count = sum(1 for c in candidates if c.get("track") == "ai-signal")
    ent_count = sum(1 for c in candidates if c.get("track") == "enterprise")
    logger.info(f"  AI-signal: {ai_count} | Enterprise: {ent_count}")
    logger.info(f"  Skipped: {len(skipped)} (archived/fork/license/stars/size)")
    logger.info(f"  Below threshold: {len(below_threshold)}")

    for c in candidates:
        ci_flag = "✓CI" if c.get("quality", {}).get("has_ci") else ""
        test_flag = "✓Tests" if c.get("quality", {}).get("has_tests") else ""
        logger.info(f"  ✓ {c['repo']} (score={c['score']}, stars={c.get('stars', '?')}, {c.get('track', '?')}) {ci_flag} {test_flag}")

    # ── Output ───────────────────────────────────────────────
    if not dry_run:
        output_dir = os.path.join(repo_root, "results")
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, "candidates.json")
        output = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "discovery_params": {
                "min_score": min_score,
                "max_candidates": max_candidates,
                "since_days": since_days,
                "track": track,
            },
            "summary": {
                "total_searched": len(all_candidates),
                "qualified": len(qualified),
                "returned": len(candidates),
                "skipped": len(skipped),
                "below_threshold": len(below_threshold),
                "track_breakdown": {
                    "ai_signal": ai_count,
                    "enterprise": ent_count,
                },
            },
            "candidates": candidates,
            "skipped": skipped[:20],
        }
        with open(output_path, "w") as f:
            json.dump(output, f, indent=2)
        logger.info(f"Wrote {output_path}")

    return candidates


def update_training_repos(repo_root: str, new_repos: list[str]) -> bool:
    """Add new repos to repos_training.json. Returns True if modified."""
    training_file = os.path.join(repo_root, "rlaif", "repos_training.json")
    with open(training_file) as f:
        data = json.load(f)

    existing = set(data.get("repos", []))
    to_add = [r for r in new_repos if r not in existing]

    if not to_add:
        logger.info("No new repos to add")
        return False

    data["repos"].extend(to_add)

    # Update categories comment
    categories = data.get("_categories", {})
    discovered_list = ", ".join(to_add)
    categories["auto_discovered"] = f"{discovered_list} ({len(to_add)})"
    data["_categories"] = categories

    with open(training_file, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    logger.info(f"Added {len(to_add)} repos to {training_file}")
    return True


# ──────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Discover high-quality training repos via GitHub API")
    parser.add_argument("--min-score", type=int, default=40, help="Minimum score threshold (default: 40)")
    parser.add_argument("--max-candidates", type=int, default=15, help="Max repos to return (default: 15)")
    parser.add_argument("--since-days", type=int, default=90, help="Look back period in days (default: 90)")
    parser.add_argument("--track", choices=["ai", "enterprise", "both"], default="both",
                        help="Discovery track: ai (vibe-coded), enterprise (production), both (default)")
    parser.add_argument("--dry-run", action="store_true", help="Preview only, don't write files")
    parser.add_argument("--update-training", action="store_true", help="Also update repos_training.json")
    parser.add_argument("--repo-root", default=".", help="Path to driftbench repo root")
    args = parser.parse_args()

    candidates = run_discovery(
        repo_root=args.repo_root,
        min_score=args.min_score,
        max_candidates=args.max_candidates,
        since_days=args.since_days,
        dry_run=args.dry_run,
        track=args.track,
    )

    if not candidates:
        logger.info("No candidates found")
        return

    # Print summary table
    print("\n" + "=" * 70)
    print(f"{'Repo':<40} {'Score':>5} {'Stars':>7} {'Evidence'}")
    print("-" * 70)
    for c in candidates:
        evidence_short = "; ".join(c.get("evidence", [])[:2])
        print(f"{c['repo']:<40} {c['score']:>5} {c.get('stars', '?'):>7} {evidence_short[:40]}")
    print("=" * 70)

    if args.update_training and not args.dry_run:
        new_repos = [c["repo"] for c in candidates]
        update_training_repos(args.repo_root, new_repos)


if __name__ == "__main__":
    main()
